import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const check = process.argv.slice(2).includes("--check");
const unsupported = process.argv.slice(2).filter((argument) => argument !== "--check");
if (unsupported.length > 0) {
  throw new Error(`unsupported option(s): ${unsupported.join(", ")}`);
}

const OXC_REVISION = "5a6e37e5cf895143a5b34050c50109c46e2ae96a";
const OXC_SOURCE = `git+https://github.com/oxc-project/oxc?rev=${OXC_REVISION}#${OXC_REVISION}`;
const SHIPPING_ROOT_PACKAGE_NAMES = ["oxc_tsrx_cli", "parser_napi_binding"];
const OXC_LICENSES = [
  {
    path: "licenses/oxc/LICENSE",
    sha256: "95ced5ecf1133fbf41d409b5555c86c344f83f3b019926057ddbc07cfdcc27b3",
  },
  {
    path: "licenses/oxc/THIRD-PARTY-LICENSE",
    sha256: "77643247a04db72198cea3c8b73751091821b4d51b5448fd65501127a9db5111",
  },
];

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function tomlString(block, key, required = true) {
  const match = new RegExp(`^${key} = ("(?:[^"\\\\]|\\\\.)*")$`, "mu").exec(block);
  if (!match) {
    if (!required) return null;
    throw new Error(`Cargo.lock package is missing ${key}`);
  }
  return JSON.parse(match[1]);
}

function lockedPackages(lock) {
  const packages = new Map();
  for (const block of lock.split(/\n(?=\[\[package\]\]\n)/u)) {
    if (!block.startsWith("[[package]]")) continue;
    const name = tomlString(block, "name");
    const version = tomlString(block, "version");
    const source = tomlString(block, "source", false);
    const checksum = tomlString(block, "checksum", false);
    packages.set(`${name}\0${version}\0${source ?? "workspace"}`, { checksum, source });
  }
  return packages;
}

function shippingPackageIds(metadata: any, rootPackages: any[]) {
  const nodes = new Map<string, any>(metadata.resolve.nodes.map((node) => [node.id, node]));
  const discovered = new Set();
  const queue = rootPackages.map((rootPackage) => rootPackage.id);
  while (queue.length > 0) {
    const id = queue.pop();
    if (discovered.has(id)) continue;
    discovered.add(id);
    const node = nodes.get(id);
    if (!node) throw new Error(`Cargo metadata has no resolve node for ${id}`);
    for (const dependency of node.deps) {
      const ships = dependency.dep_kinds.some((kind) => kind.kind !== "dev");
      if (ships) queue.push(dependency.pkg);
    }
  }
  return discovered;
}

function markdownEscape(value) {
  return String(value).replaceAll("|", "\\|");
}

function sourceLabel(dependency) {
  if (dependency.sourceKind === "crates.io") {
    return `[crates.io](https://crates.io/crates/${dependency.name}/${dependency.version})`;
  }
  return `[OXC ${OXC_REVISION.slice(0, 12)}](https://github.com/oxc-project/oxc/tree/${OXC_REVISION})`;
}

function renderReport(inventory) {
  const rows = inventory.packages.map(
    (dependency) =>
      `| ${markdownEscape(dependency.name)} | ${markdownEscape(dependency.version)} | ${markdownEscape(dependency.license)} | **${markdownEscape(dependency.selectedDistributionLicense)}** | ${sourceLabel(dependency)} | ${dependency.checksum ?? "revision-pinned"} |`,
  );
  return `# Rust binary dependency licenses

This report is generated by \`scripts/generate-rust-license-inventory.ts\` from
the committed \`Cargo.lock\`. Do not edit it by hand. It covers the normal and
build dependency closure of the three binaries in \`oxc_tsrx_cli\` and the
native addon in \`parser_napi_binding\`; benchmark and development-only
dependencies are excluded.

- Cargo.lock SHA-256: \`${inventory.cargoLockSha256}\`
- Canonical OXC revision: \`${inventory.oxcRevision}\`
- Shipping third-party packages: ${inventory.packageCount}
- Accepted license policy: \`licenses/allowed-rust-license-expressions.json\`
- Every dual/multi-license expression has an explicit selected distribution
  license. In particular, \`self_cell\` is distributed under Apache-2.0, not
  GPL-2.0-only.
- Canonical OXC texts: \`licenses/oxc/LICENSE\` and
  \`licenses/oxc/THIRD-PARTY-LICENSE\`

| Package | Version | Cargo license expression | Selected distribution license | Locked source | Checksum |
| --- | --- | --- | --- | --- | --- |
${rows.join("\n")}
`;
}

async function assertCanonicalOxcFiles() {
  for (const expected of OXC_LICENSES) {
    const contents = await readFile(join(root, expected.path)).catch(() => null);
    if (!contents) throw new Error(`missing canonical OXC legal file: ${expected.path}`);
    const actual = sha256(contents);
    if (actual !== expected.sha256) {
      throw new Error(`${expected.path} SHA-256 mismatch: ${actual} != ${expected.sha256}`);
    }
  }
}

await assertCanonicalOxcFiles();
const [lock, policy] = await Promise.all([
  readFile(join(root, "Cargo.lock"), "utf8"),
  readFile(join(root, "licenses/allowed-rust-license-expressions.json"), "utf8").then(JSON.parse),
]);
const metadata: any = JSON.parse(
  execFileSync("cargo", ["metadata", "--locked", "--format-version", "1"], {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 128 * 1024 * 1024,
  }),
);
const rootPackages = SHIPPING_ROOT_PACKAGE_NAMES.map((name) => {
  const matches = metadata.packages.filter(
    (candidate) => candidate.name === name && candidate.source === null,
  );
  if (matches.length !== 1) {
    throw new Error(`Cargo metadata must contain exactly one workspace package named ${name}`);
  }
  return matches[0];
});

const shippingIds = shippingPackageIds(metadata, rootPackages);
const lockIndex = lockedPackages(lock);
const allowed = new Set<string>(policy.allowedExpressions as string[]);
const selections: Record<string, string> = policy.selectedDistributionLicenseByExpression;
if (!selections || typeof selections !== "object" || Array.isArray(selections)) {
  throw new Error("Rust license policy has no selectedDistributionLicenseByExpression map");
}
for (const expression of allowed) {
  if (typeof selections[expression] !== "string" || selections[expression].length === 0) {
    throw new Error(`Rust license policy has no distribution selection for: ${expression}`);
  }
}
for (const expression of Object.keys(selections)) {
  if (!allowed.has(expression)) {
    throw new Error(`Rust license policy selects an expression that is not allowed: ${expression}`);
  }
}
const dependencies = metadata.packages
  .filter((dependency) => shippingIds.has(dependency.id) && dependency.source !== null)
  .map((dependency) => {
    if (!dependency.license) {
      throw new Error(`${dependency.name}@${dependency.version} has no Cargo license expression`);
    }
    if (!allowed.has(dependency.license)) {
      throw new Error(
        `${dependency.name}@${dependency.version} has unreviewed license expression: ${dependency.license}`,
      );
    }
    const locked = lockIndex.get(
      `${dependency.name}\0${dependency.version}\0${dependency.source}`,
    );
    if (!locked) {
      throw new Error(
        `${dependency.name}@${dependency.version} (${dependency.source}) is absent from Cargo.lock`,
      );
    }
    const sourceKind = dependency.source.startsWith("registry+") ? "crates.io" : "oxc-git";
    if (sourceKind === "crates.io" && !locked.checksum) {
      throw new Error(`${dependency.name}@${dependency.version} has no locked registry checksum`);
    }
    if (sourceKind === "oxc-git" && dependency.source !== OXC_SOURCE) {
      throw new Error(`unreviewed Git dependency in shipping closure: ${dependency.source}`);
    }
    return {
      name: dependency.name,
      version: dependency.version,
      license: dependency.license,
      selectedDistributionLicense: selections[dependency.license],
      sourceKind,
      source: dependency.source,
      checksum: locked.checksum,
    };
  })
  .sort((left, right) =>
    `${left.name}\0${left.version}\0${left.source}`.localeCompare(
      `${right.name}\0${right.version}\0${right.source}`,
    ),
  );

const oxcPackages = dependencies.filter((dependency) => dependency.sourceKind === "oxc-git");
if (oxcPackages.length < 12 || oxcPackages.some((dependency) => dependency.license !== "MIT")) {
  throw new Error("canonical OXC dependency closure is missing or has an unexpected license");
}
const selfCell = dependencies.find((dependency) => dependency.name === "self_cell");
if (
  !selfCell ||
  selfCell.license !== "Apache-2.0 OR GPL-2.0-only" ||
  selfCell.selectedDistributionLicense !== "Apache-2.0"
) {
  throw new Error("self_cell must explicitly select Apache-2.0 for distribution");
}

const inventory = {
  schemaVersion: 2,
  generatedBy: "scripts/generate-rust-license-inventory.ts",
  rootPackages: rootPackages.map((rootPackage) => `${rootPackage.name}@${rootPackage.version}`),
  cargoLockSha256: sha256(lock),
  oxcRevision: OXC_REVISION,
  licenseSelectionPolicy:
    "Each Cargo expression is reviewed; selectedDistributionLicense records the basis used for binary distribution.",
  packageCount: dependencies.length,
  packages: dependencies,
};
const outputs = new Map([
  ["licenses/rust-dependencies.json", `${JSON.stringify(inventory, null, 2)}\n`],
  ["licenses/RUST_DEPENDENCIES.md", renderReport(inventory)],
]);

await mkdir(join(root, "licenses"), { recursive: true });
for (const [path, expected] of outputs) {
  const absolute = join(root, path);
  if (check) {
    const actual = await readFile(absolute, "utf8").catch(() => null);
    if (actual !== expected) {
      throw new Error(`${path} is stale; run pnpm run licenses:rust:generate`);
    }
  } else {
    await writeFile(absolute, expected);
  }
}

process.stdout.write(
  `${check ? "verified" : "generated"} ${dependencies.length} locked shipping dependency licenses\n`,
);
